name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  test:
    uses: "traefik/traefik-helm-chart/.github/workflows/test.yml@master"
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global --add safe.directory /charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          config: ./.github/chart-releaser.yaml
        env:
          CR_OWNER: traefik
          CR_GIT_REPO: charts
          CR_TOKEN: "${{ secrets.CHARTS_TOKEN }}"
